### ISSUE TITLE
ENUM Marktrolle->`NB` sollte in `VNB` umgenannt werden, um Interpretation als ÜNB auszuschließen

### ISSUE THREAD

**Issue by hf-kklein** [bo4e/BO4E-python#113]
To prevent any ambiguities with UENB

https://github.com/Hochfrequenz/BO4E-python/blob/46e660d46c341aa55d88926fe29b8d1a91d549a7/src/bo4e/enum/marktrolle.py#L11

**Comment by snsttr** [comment]
Die offizielle Bezeichnung der Marktrolle lautet "Netzbetreiber", weshalb wir uns auch das passende Kürzel "NB" geeinigt haben.
