### ISSUE TITLE
Remove EDIFACT Qualifiers from Messwertstatuszusatz ENUM

### ISSUE THREAD

**Issue by hf-kklein** [bo4e/BO4E-python#116]
relates to #115

we're not rebuilding edifact but creating a readable standard. the edifact value should be part of f.e. documentation but not part of the standard

**Comment by snsttr** [comment]
Gerade um die Lesbarkeit zu erhöhen würden wir bei der aktuellen Variante bleiben. Somit hat man sowohl immer die Codenummer als auch die Beschreibung mit im ENUM Wert.
