### ISSUE TITLE
How to interprete `netzkontonummern` in COM StandorteigenschaftenGas

### ISSUE THREAD

**Issue by hf-krechan** [bo4e/BO4E-python#230]
I am not sure, how to interpret the attribute `netzkontonummern`.
At the moment it is implemented as a List of strings which must have at least one entry and a maximum length of two.

https://www.bo4e.de/dokumentation/komponenten/com-standorteigenschaftengas

**Comment by snsttr** [comment]
Ein Standort konnte bis zum 31.10.2021 zu einem oder maximal zwei Marktgebieten gehören. Deshalb die Angabe "[1..2]".

**Comment by hf-kklein** [comment]
https://github.com/bo4e/BO4E-python/blob/45bec8edc66aef53aa91b352d126e6df67e34c9d/src/bo4e/com/standorteigenschaftengas.py#L27

ist im momemtn so umgesetzt.
