### ISSUE TITLE
Gibt es eine Vorgabe, wie leere Listen ohne Mindestlänge zu serialisieren sind? Dürfen Listen nullable sein?

### ISSUE THREAD

**Issue by hf-aschloegl** [bo4e/BO4E-python#274]
Sollten Listen die keine Mindestanzahl einträge haben per default als `None/null` serialisiert werden (oder ggf. auch gar nicht) oder immer als leere Liste `[ ]`?

Im Hinblick auf eine Integration verschiedener Libraries wäre das eine wichtige Frage.

example: https://github.com/Hochfrequenz/BO4E-python/pull/273#discussion_r773182098

**Comment by hf-kklein** [comment]
So umgesetzt in #617
