### ISSUE TITLE
Unterschied zwischen Beschreibung und Bezeichnung unklar

### ISSUE THREAD

**Issue by hf-aschloegl** [bo4e/BO4E-python#280]
Am Besten durch Beispiele klarer machen.

see: https://github.com/Hochfrequenz/BO4E-python/pull/275#discussion_r773205618

**Comment by snsttr** [comment]
Wir denken, dass hier nicht unbedingt eine genauere Beschreibung erfolgen muss. Eine Bezeichnung definiert den Namen des Auf- oder Abschlags, die Beschreibung gibt die Möglichkeit diesen näher zu erläutern.
In dem Zusammenhang haben wir allerdings entschieden, dass das Feld "beschreibung" optional wird.

Beispiel:
- Bezeichnung: "KWK Aufschlag"
- Beschreibung: "KWK Aufschlag gemäß Kraft-Wärme-Kopplungsgesetz"

**Comment by snsttr** [comment]
Da es bei Tarifen sehr viele verschiedene Varianten von Auf- und Abschlägen gibt, wurde hier kein ENUM als Referenz definiert. Deshalb sind tatsächlich beide Felder willkürlich befüllbar.

**Comment by hf-kklein** [comment]
Hi Annika, kannst du da vllt bei Gelegenheit zwei Sätze im Docstring ergänzen?

**Comment by snsttr** [comment]
Das Feld "beschreibung" ist jetzt optional. Siehe https://www.bo4e.de/dokumentation/komponenten/com-positionsaufabschlag/04-03-2022
