### ISSUE TITLE
Buendelvertrag Vererbung ist vermutlich falsch

### ISSUE THREAD

**Issue by hf-kklein** [bo4e/BO4E-python#312]
![grafik](https://user-images.githubusercontent.com/23094997/148682869-fb595db2-3eee-4d91-8fb5-6a677e291da0.png)
https://www.bo4e.de/dokumentation/geschaeftsobjekte/bo-buendelvertrag

Der Buendelvertrag sollte meiner Meinung nach _nicht_ von Vertrag erben. Denn wenn alle Eigenschaften der Einzelverträge alle gleich sind (das impliziert ja die Vererbung von einem Vertrag), warum brauchen wir dann die Einzelverträge überhaupt?

**Comment by snsttr** [comment]
Wir konnten die Anmerkungen nachvollziehen und haben das Konstrukt des Bündelvertrags angepasst, siehe: https://www.bo4e.de/dokumentation/geschaeftsobjekte/bo-buendelvertrag/02-03-2022

**Comment by hf-kklein** [comment]
Todo: Irgendjemand müsste jetzt die Änderungen in der Referenz-Implementierung nachziehen.

**Comment by hf-kklein** [comment]
in #422 erledigt
