### ISSUE TITLE
Beschreibung für Tarifberechnungsparameter fehlt komplett

### ISSUE THREAD

**Issue by hf-kklein** [bo4e/BO4E-python#328]

**Comment by snsttr** [comment]
Wir haben den fehlenden Satz ergänzt: https://www.bo4e.de/dokumentation/komponenten/com-tarifberechnungsparameter

**Comment by hf-kklein** [comment]
Hi Leon, bitte den Satz in die doku übernehmen und einen PR dazu aufmachen
