### ISSUE TITLE
BO PreisblattNetznutzung: Is the bilanzierungsmethode required?

### ISSUE THREAD

**Issue by hf-kklein** [bo4e/BO4E-python#330]
The [BO4E documentation](https://www.bo4e.de/dokumentation/geschaeftsobjekte/bo-preisblattnetznutzung) does not mention if this is a required or optional attribute?
How do you know?

_Originally posted by @hf-krechan in https://github.com/Hochfrequenz/BO4E-python/pull/325#r789682952_

**Comment by snsttr** [comment]
Ja, tatsächlich fehlt hier die Angabe, dass es sich um ein Pflichtfeld handelt.
Die Korrektur haben wir hier schon vorgenommen: https://www.bo4e.de/dokumentation/geschaeftsobjekte/bo-preisblattnetznutzung

**Comment by hf-kklein** [comment]
https://github.com/bo4e/BO4E-python/blob/45bec8edc66aef53aa91b352d126e6df67e34c9d/src/bo4e/bo/preisblattnetznutzung.py#L29

ist bereits so umgesetzt.
