### ISSUE TITLE
BO PreisblattMessung hat Eigenschaft `zaehler`, die aber kein Zaehler ist

### ISSUE THREAD

**Issue by hf-kklein** [bo4e/BO4E-python#333]
sondenr `Geraeteeigenschaften`

Warum?

![grafik](https://user-images.githubusercontent.com/23094997/150552861-859ab271-32eb-41e7-95b7-65ff95f4dda0.png)

**Comment by snsttr** [comment]
Wir haben festgestellt, dass die Darstellung der Messpreise und anderer Informationen im Bereich der Preisblätter aktuell insgesamt nicht optimal ist. PM prüft das einmal, damit die Struktur hier insgesamt überarbeitet werden kann.

**Comment by hf-aschloegl** [comment]
Sollte durch https://github.com/bo4e/BO4E-python/pull/630 gefixt sein.
