### ISSUE TITLE
Do we still need the `stringcase` dependency?

### ISSUE THREAD

**Issue by hf-kklein** [bo4e/BO4E-python#355]
you introduced it in https://github.com/Hochfrequenz/BO4E-python/pull/27/commits/123b8e738b8ad074af009e143db0f4710eb032cc
https://github.com/Hochfrequenz/BO4E-python/blob/21cceaff2133a9c2ea59d3cc1d41f8c8b5ea1e93/requirements.in#L5

**Comment by hf-krechan** [comment]
nope not needed anymore. Fixed in #393
