### ISSUE TITLE
Umsatzsteuer 16% nicht unterstützt

### ISSUE THREAD

**Issue by hf-kklein** [bo4e/BO4E-python#356]
Das Steuerkennzeichen sollte auch einen Eintrag `UST_16` enthalten.
See https://github.com/Hochfrequenz/go-bo4e/issues/78

**Comment by snsttr** [comment]
Wir haben den Wert "UST_16" ergänzt (siehe https://www.bo4e.de/dokumentation/enumerations/enum-steuerkennzeichen/02-03-2022). Kann somit hier nachgezogen werden.
