### ISSUE TITLE
ENUM Rechnungstyp: `TURNUSRECHNUNG` fehlt

### ISSUE THREAD

**Issue by hf-kklein** [bo4e/BO4E-python#357]
Nach unseren Aufzeichnungen, war mindestens die Turnusrechnung 2020 noch teil des ENUMs Rechnungstyp und nicht nur im NNRechnungstyp vorhanden.

Siehe https://github.com/Hochfrequenz/go-bo4e/issues/78 bzw https://github.com/Hochfrequenz/go-bo4e/issues/82

**Comment by snsttr** [comment]
Unserer Historie nach war "TURNUSRECHNUNG" nie Bestandteil des "ENUM Rechnungstyp", sondern immer nur des "ENUM NNRechnungstyp".

**Comment by hf-kklein** [comment]
Ich konnte das Problem nachstellen:
Als wir irgendwann vor 2021 die Enums halbautomatisch gescraped haben, war die Turnusabrechnung noch Teil des Rechnungstyps:
https://web.archive.org/web/20201019234643/https://www.bo4e.de/dokumentation/enumerations/enum-rechnungstyp

Vermutlich hatten wir es daher gezogen, in der .NET lib war das seit dem initial commit https://github.com/Hochfrequenz/BO4E-dotnet/commit/2cd25c9bd759ecf743f2f023b718bef0507cccf8#r67792696

Müssen bei das langfristig wieder ausschleichen in der .NET implementierung.
