### ISSUE TITLE
ENUM Rechnungstyp: MSBRECHNUNG fehlt

### ISSUE THREAD

**Issue by hf-kklein** [bo4e/BO4E-python#358]
Die MSB-Rechnung ist ein sinnvoller Rechnungstyp und bisher vom offiziellen BO4E nicht unterstützt.
Siehe https://github.com/Hochfrequenz/go-bo4e/issues/78

**Comment by snsttr** [comment]
Den Wert "MESSSTELLENBETRIEBSRECHNUNG" gibt es bereits im "ENUM Rechnungstyp". Reicht das so nicht aus?

**Comment by hf-kklein** [comment]
ja, das reicht :)
