### ISSUE TITLE
ENUM Mengeneinheit: `ANZAHL` fehlt (wurde in `STUECK` umbenannt)

### ISSUE THREAD

**Issue by hf-kklein** [bo4e/BO4E-python#359]
das breakt bestehende Implementierungen

**Comment by snsttr** [comment]
Die Anpassung von "ANZAHL" zu "STUECK" wurde 2019 vorgenommen, ohne dies als neue Version zu kennzeichnen. Dieser Breaking Change wurde in Kauf genommen, zukünftig müssen wir das aber natürlich vermeiden.
