### ISSUE TITLE
ZaehlergroesseGas Property is missing for BO Zaehler

### ISSUE THREAD

**Issue by hf-kklein** [bo4e/BO4E-python#366]
https://github.com/bo4e/BO4E-python/blob/45bec8edc66aef53aa91b352d126e6df67e34c9d/src/bo4e/bo/zaehler.py#L61

Wahrscheinlich, weil wir den Zähler schon vor dem 15.12.21 gebaut hatten:
https://www.bo4e.de/dokumentation/geschaeftsobjekte/bo-zahler/15-12-2021

**Comment by snsttr** [comment]
Wie in #368 beschrieben, wird das Feld hier weiter benötigt, es soll aber auf das ENUM Geraetemerkmal verweisen.

**Comment by hf-aschloegl** [comment]
Sollte durch https://github.com/bo4e/BO4E-python/pull/630 gefixt sein.
