### ISSUE TITLE
`ZaehlergroesseGas` ist redundant und überschneidet sich mit dem ENUM `Geraetemerkmal`; Verwendung von ZaehlergroesseGas im Zaehler ist inkonsistent

### ISSUE THREAD

**Issue by hf-kklein** [bo4e/BO4E-python#368]
Am 15.12.21 wurde in der Dokumentation die [ZaehlergroesseGas](https://www.bo4e.de/dokumentation/enumerations/enum-zaehlergroesse) eingeführt.
Die dort beschriebenen Enum-Werte überschneiden sich aber mit denen des [Geraetemerkmals](https://www.bo4e.de/dokumentation/enumerations/enum-geraetemerkmal).

Außerdem wird die ZaehlergroesseGas seit 15.12.21 auch im BO Zaehler verwendet (siehe auch #366).
Das ist meiner Meinung nach inkonsistent: Warum ist die Gas-spezifische Zaehlergroesse eine direkte Eigenschaft des Zaehlers, aber die bereits vorhandenen Geraetemerkmale hängen nur am [COM Geraet](https://www.bo4e.de/dokumentation/komponenten/com-geraet), was aber laut Dokumentation gerade all die Geräte umfasst, die ausdrücklich _keine_ Zaehler sind.

https://github.com/bo4e/BO4E-python/blob/45bec8edc66aef53aa91b352d126e6df67e34c9d/src/bo4e/com/geraet.py#L19

![grafik](https://user-images.githubusercontent.com/23094997/152491588-3611dca5-2da4-4b2e-b6a8-ad26a606e521.png)

Trotzdem enthält das ENUM Geraetemerkmal auch ganz offensichtliche Zählereigenschaften (Ein/Zwei/Mehrtarifzähler).

Abgesehen von der Redundanz: Wir bräuchten auch eine Möglichkeit die Infos aus dem Geraetemerkmal an den Zähler zu hängen, so wie mit der ZaehlergroesseGas nun geschehen.

**Comment by snsttr** [comment]
Wir haben den Sachverhalt geprüft und konnten nachvollziehen, dass hier Optimierungsbedarf besteht. Wir stellen das Ticket aber noch einmal zurück, um die Details klären zu können.

**Comment by snsttr** [comment]
Wir hätten jetzt folgenden Vorschlag: Das ENUM ZaehlergroesseGas entfällt. Im BO Zaehler wird stattdessen im Feld "zaehlergroesseGas" auf das ENUM Geraetemerkmal referenziert. Zudem werden im ENUM Geraetemerkmal die Präfixe "GAS_" entfernt und die fehlenden Werte ergänzt:

- G4000
- G6500
- G10000
- G12500
- G16000

**Comment by hf-kklein** [comment]
Hi Tim, wir sind heute wieder über dieses Problem gestolpert. Die von euch vorgeschlagene Lösung ist aus unserer Sicht nicht zielführend, weil sie das ursprüngliche Problem ("Gerätemerkmal und ZaehlergroesseGas überschneiden sich") nicht löst sondern eher noch verschärft.

Das Problem wird deutlich, wenn man alles unter der Prämisse betrachtet, dass ein Enum genau einen fachlichen Aspekt/ein fachliches Attribut abbilden soll:

- Die `ZaehlergroesseGas` sollte die Zählergröße von Gaszählern modellieren und keineModems oder Anzahl Tarife
- `Geraetemerkmal` sollte Gerätemerkmale modellieren`und keine Zählergrößen, Zähler- oder Gerätetypen
- ein Geraetetyp (z.: `TEMPERATUR_MU`) sollte nicht vom gleichen Enum abgebildet werden wie z.B. ein Enum, das Zählergrößen modelliert.

Das sind alles verschiedene Dinge, die nicht in ein gemeinsames Enum sollten, weil es weder fachlich noch technisch zweckmäßig ist.

Kurzum: Wir hätten lieber mehr als weniger Enums.

Ich glaube das Grundproblem ist, dass wir etwas verbissen die Anzahl der Typen gleich halten wollen und stattdessen für verschiedene fachliche Aspekte dafür die Bedeutung der Typen allgemein und der Enums im Speziellen aufweichen. Besser wäre es vielleicht saubere neue Typen (z.B. Gaszaehler (erbt von Zaehler)) zu etablieren anstatt die bestehenden Typen soweit aufzubiegen, dass wir mit ihnen alles abbilden können aber am Ende niemand durchblickt.

Das ist glaube ich auch das Grundproblem bei Zähler, Gerät, Hardware usw (siehe auch #373).

**Comment by hf-aschloegl** [comment]
Sollte durch https://github.com/bo4e/BO4E-python/pull/630 gefixt sein.
