### ISSUE TITLE
Liste von `Hardware` heißt `Geraete`: Was ist der Unterschied zwischen Hardware und Geraet/Geraeteeigenschaften?

### ISSUE THREAD

**Issue by hf-kklein** [bo4e/BO4E-python#373]
https://github.com/bo4e/BO4E-python/blob/28b12f853c8a496d14b133759b7aa2d6661f79a0/src/bo4e/bo/messlokation.py#L67

Im BO Messlokation existiert (im Speziellen) eine Liste von Hardware, die aber `geraete` heißt.

Da stellt sich allgemein die Frage: Was ist der Unterschied zwischen COM Geraet und COM Hardware?
Wann soll was verwendet werden?
Das COM Hardware scheint identisch mit dem COM Geraeteeigenschaften zu sein
![grafik](https://user-images.githubusercontent.com/23094997/160414706-ade5b419-d2bc-47f1-abdd-06470155c4b0.png)
![grafik](https://user-images.githubusercontent.com/23094997/160414846-f2a14f86-8aea-486e-bd7a-fadebc83e7cf.png)

**Comment by snsttr** [comment]
Wir haben das geprüft und hätten die Idee die COM Hardware entfallen zu lassen. Sie wird nur im BO Messlokation verwendet. Dort könnten wir die Referenz auf COM Geraeteeigenschaften ändern. In der COM Geraeteeigenschaften müsste dann nur noch ein optionales Feld "bezeichnung" ergänzt werden, damit die Abbildung wieder so möglich ist, wie es in der COM Hardware der Fall war.
Wenn das aus eurer Sicht so passt, könnt ihr das gerne direkt umsetzen.

**Comment by hf-kklein** [comment]
Hi Leon, kannst du dafür bitte mal bei Gelegenheit einen PR aufmachen?

Den breaking change (was das obsoleten einer klasse definitiv ist) bilden wir dann über die versionierung ab ;)

**Comment by hf-aschloegl** [comment]
Sollte durch https://github.com/bo4e/BO4E-python/pull/630 gefixt sein.
