### ISSUE TITLE
Visualiserung / UML-Diagramme

### ISSUE THREAD

**Issue by hf-kklein** [bo4e/BO4E-python#374]
Die Anforderung an die UML-Diagramme sind:

- [ ] Die Diagramme sollen mindestens teilweise automatisiert erstellt werden um Schiefständen zwischen Doku und Code-Realität vorzubeugen.
- [ ] Die Diagramme sollen die lowerCamelCase Nomenklatur verwenden.
- [ ] Die Diagramme sollen 1:[0-n] Kardinalitäten sauber abbilden können.
- [ ] Die Diagramme sollen vollständig aber nicht unübersichtlich sein.

Dieses Ticket dient dazu, unsere bisherigen Versuche mit ihren jeweiligen Vor- und Nachteilen zu dokumentieren.

**Comment by hf-krechan** [comment]
# Pyreverse and Graphviz  

## Requirements
* pylint: `pip install pylint`
* graphviz 
   * macOS: `brew install graphviz`

## How to

```bash
// create .dot file
pyreverse src/bo4e/bo
// draw uml diagram
dot -Tpng classes.dot -o bo4e-uml.png
```

Man kann damit verschiedene Formate erstellen

```bash
dot -Kdot -Tpng classes.dot -o bo4e-uml-dot.png
dot -Kneato -Tpng classes.dot -o bo4e-uml-neato.png
dot -Ktwopi -Tpng classes.dot -o bo4e-uml-twopi.png
dot -Kcirco -Tpng classes.dot -o bo4e-uml-twopi.png
dot -Ktwopi -Tpng classes.dot -o bo4e-uml-twopi.png
dot -Kcirco -Tpng classes.dot -o bo4e-uml-circo.png
dot -Kfdp -Tpng classes.dot -o bo4e-uml-fdp.png
dot -Kosage -Tpng classes.dot -o bo4e-uml-osage.png
dot -Kpatchwork -Tpng classes.dot -o bo4e-uml-patchwork.png
dot -Ksfdp -Tpng classes.dot -o bo4e-uml-sfdp.png
```

Diese sehen unterschiedlich gut aus

### circo
![bo4e-uml-circo](https://user-images.githubusercontent.com/68426071/165286041-c3915270-4eb8-4a16-9fe6-d01779d31b65.png)

### dot
![bo4e-uml-dot](https://user-images.githubusercontent.com/68426071/165285967-fbeec6ad-13ff-4f3d-b7d5-67b11a93b077.png)

### fdp
![bo4e-uml-fdp](https://user-images.githubusercontent.com/68426071/165286150-025d5095-3284-47ab-8763-62b7f395effb.png)


### neato
![bo4e-uml-neato](https://user-images.githubusercontent.com/68426071/165286168-51c4e361-7c49-44f4-9d40-d4935eb313e7.png)

### osage

![bo4e-uml-osage](https://user-images.githubusercontent.com/68426071/165286223-594ee724-66c3-40c9-927e-0006227fe5ee.png)

### patchwork
![bo4e-uml-patchwork](https://user-images.githubusercontent.com/68426071/165286248-3be1498b-c954-43e2-a7b3-475ac027dea3.png)

### sfdp
![bo4e-uml-sfdp](https://user-images.githubusercontent.com/68426071/165286320-40fa619f-f2a5-43c8-8fbd-a6a999fd7523.png)

### twopi
![bo4e-uml-twopi](https://user-images.githubusercontent.com/68426071/165286361-9696c942-095b-43ea-8d5a-d5773c719739.png)

## Probleme

* Aktuell werden die Klassen **und** ihre entsprechenden Schemata in dem UML abgebildet.
* Die Komponenten sind bei dem Befehl nicht dabei. Führt man den Befehl `pyreverse src/bo4e/` an, so sollten auch die COMs und ENUMs Teil des Diagramms sein.

## Result

✅ Die Diagramme sollen mindestens teilweise automatisiert erstellt werden um Schiefständen zwischen Doku und Code-Realität vorzubeugen.
✅  Die Diagramme sollen die lowerCamelCase Nomenklatur verwenden.
❌  Die Diagramme sollen 1:[0-n] Kardinalitäten sauber abbilden können.
❌  Die Diagramme sollen vollständig aber nicht unübersichtlich sein.

**Comment by hf-kklein** [comment]
@snsttr die json-schemas liegen auch alle im git (also außerhalb von sphinx)
https://github.com/bo4e/BO4E-python/tree/main/json_schemas/bo

**Comment by hf-kklein** [comment]
For the record: I also tried gituml:
https://plantuml.atug.com/svg/nLDDJyCm3BtdLrZY0eZr1qnJ9H1IB-mqE5TfwgvXIr8bALC7_7UyDcND-13Y09NQEiyljf_ZY2rt3gxr6WlZuPa1FLnNbg_HOaMltWUiPxYI-rP527tHHeZ6Mfr2hHgXGkeIAokT7vOczrtJcwxXrcDljjgZtQCKjKQRVqprkN-I-8bRoOcasIjZ6JfHSwoyCyKZRZmiNcQZPZPglvpDKhWnzrq3yx6go4VIqKk5v8wx4R5MlGZY13MHyrZ8mKcbJs8DudvC3reZVbYuKJpHZttuIilaF4w2kSQYg8-flstwh_OEcfcO3k5ArAZuVunYNqQkkSA_7SUWU3AK0nBw4iBbJGUBXJ9bkyKq9HFEbrV6YbgM5q30sIstcnNop29gQXybcknCalTBFWTXjETIEqW_fuI28gB0WqQeZ3dyCYIXD4Cb51raqZyixs2tsoLhIMUoJOHHx0q0

https://gituml.com/ztree_scratchpad also I do have a paid account but the problems described above are testable/reproducable with the free version, too.

**Comment by lord-haffi** [comment]
Does it have to be in one diagram? 'Cause with `pyreverse` you can define the scope so I think it should be possible to make several little UML diagram which could easily be placed inside the docs with the extension [sphinx.ext.graphviz](https://www.sphinx-doc.org/en/master/usage/extensions/graphviz.html).
