### ISSUE TITLE
Some of the Classes/Modules are not part of the Sphinx Docs

### ISSUE THREAD

**Issue by hf-kklein** [bo4e/BO4E-python#375]
Some of the modules are not documented in Sphinx
![grafik](https://user-images.githubusercontent.com/23094997/165298124-ffbcd895-9881-47b1-81fe-d90913b2ff69.png)

**Comment by hf-kklein** [comment]
Hi Annika, kannst du dir das mal ansehen? Als alte Sphinx-Expertin?

**Comment by hf-kklein** [comment]
Hi @lord-haffi, könntest du dir das bei Gelegenheit ansehen? Unsere Python Crew (namentlich Annika) können dir mit Sphinx helfen. Es läuft im Wesentlichen über `tox -e docs`. Damit kannst du die Doku lokal bauen und so rausfinden, warum fremdkosten, energiemenge usw (siehe oben) keinen Abschnitt in der autogenerierten Doku bekommen.

**Comment by lord-haffi** [comment]
Also wenn ich `tox -e docs` ausführe und mir die generierten Dateien in `.tox\docs\tmp\html` anschaue, sieht das aus wie es sollte... Was hast du denn ausgeführt bzw. was funktioniert denn nicht?
![grafik](https://user-images.githubusercontent.com/49658102/173180984-16044243-6cc9-4bd0-b5cd-288815e3b726.png)

**Comment by hf-kklein** [comment]
@hf-krechan wie wird denn die doku auf read-the-docs erstellt? ich nehme mal an nach dem gleichen verfahren?

**Comment by hf-krechan** [comment]
Korrekt. Das sollte nach dem selben Verfahren laufen wie die Befehle die wir in see tox.ini Datei hinterlegt haben

**Comment by hf-aschloegl** [comment]
Das Schließen war automatisch mit dem PR merge, aber es funktioniert 🚀
![grafik](https://user-images.githubusercontent.com/73470827/173387706-fe77b89d-e45e-4ee5-8290-f8e3ed9668ca.png)
