### ISSUE TITLE
Bildliche Darstellung/Abhängigkeitsmodell der BO im Gesamtzusammenhang

### ISSUE THREAD

**Issue by EVE-Carlos** [bo4e/BO4E-python#511]
Für ein besseres Verständnis und Übersichtlichkeit sollte für die BO ein Abhängigkeitsmodell gezeichnet werden. Aktuell ist es für dritte und Neuverwender sehr schwer das BO Modell zu verstehen und sich in die BO einzuarbeiten. Dies soll mit dem Abhängigkeitsmodell vereinfacht werden. Anschließend können mit dem Modell die BO Inhaltlich besser überprüft und optimiert werden. Teilweise können auch BO’s nicht verwendet, da Abhängigkeit zu andern BO’s vorausgesetzt wird und dies auf den ersten Blick nicht sichtbar wird.

**Comment by hf-kklein** [comment]
Verstehe ich dich richtig: Ihr wollt also UML-Diagramme, die die ganze Tiefe abbilden, nicht nur die erste Ebene, also dass es z.b. hier rechts noch weitergeht und die ganzen verwendeten COMs und Strukturen noch weiter aufgefächert würden?
![grafik](https://github.com/bo4e/BO4E-python/assets/23094997/ab731b0b-80ed-463e-8e5c-fbc80c6aae04)

**Comment by hf-kklein** [comment]
ok, das wären dann also die UMLs, die jetzt schon auf readthedocs sind. hängt dann zusammen mit #398

**Comment by hf-fvesely** [comment]
@EVE-Carlos https://bo4e-python.readthedocs.io/en/latest/api/bo4e.html Wir hoffen, dass dieses Ticket mit der verlinkten Dokumentation hinreichend erfüllt ist und schließen dieses Issue.
