### ISSUE TITLE
BO Rechnung: Fälle, bei welchen die Felder "rechnungsersteller" und "rechnungsempfaenger" nicht benötigt werden (MaKo), können nicht abgebildet werden.

### ISSUE THREAD

**Issue by JonasSchneegans** [bo4e/BO4E-python#543]
**Die fachliche Anforderung**

Im Mako kontext werden die Felder "rechnungsersteller" und "rechnungsempfaenger" nicht benötigt, bzw sie werden als Marktpartner modeliert.

**Gibt es schon eine Idee zur Umsetzung?**
Die Felder "rechnungsersteller" und "rechnungsempfaenger" können optional gemacht werden.

**Comment by hf-kklein** [comment]
erledigt in #617 / v1.0.0
