### ISSUE TITLE
dem BO Zähler fehlt die Information, wie Messwerte erfasst werden

### ISSUE THREAD

**Issue by hf-kklein** [bo4e/BO4E-python#575]
**Die fachliche Anforderung**

Wir wollen in Zählern modellieren, wie der Zähler ausgelesen werden kann.

**Gibt es schon eine Idee zur Umsetzung?**

_Hier als Text (oder gerne auch Pseudo-Code) einfügen, wie eine Lösung aussehen könnte; Z.B.:_
Das ENUM `Messwerterfassung` soll zwei Werte enthalten
* `FERNAUSLESBAR`
* `MANUELL_AUSLESBAR`

Das BO Zähler soll um ein entsprechendes Feld `messwerterfassung: Optional[Messwerterfassung]` erweitert werden.

**Comment by hf-aschloegl** [comment]
Sollte durch https://github.com/bo4e/BO4E-python/pull/630 gefixt sein.
