### ISSUE TITLE
Fehlendes Steuerkennzeichen für `VST_16`

### ISSUE THREAD

**Issue by hf-kklein** [bo4e/BO4E-python#580]
Analog `UST_16` sollte es auch `VST_16` geben

**Comment by hf-krechan** [comment]
Ja wird übernommen.
![image](https://github.com/bo4e/BO4E-python/assets/68426071/8b0fb4b4-e22e-44d5-a679-aca6de82b136)

**Comment by hf-kklein** [comment]
@OLILHR @hf-crings Bitte erweitert das Enum `Steuerkennzeichen` um die 16%ige Vorsteuer.
- [ ] von main abbranchen
- [ ] Enum wert ergänzen
- [ ] schauen, dass die CI actions grün sind
- [ ] ggf. müsst ihr tox -e json_schemas einmalig ausführen um auch die Schemas neu zu generieren... Fragt leon oder @hf-krechan, was hier der aktuelle stand ist)
- [ ] @hf-krechan als reviewer assignen
