### ISSUE TITLE
Remove comments which say `# optional attributes`

### ISSUE THREAD

**Issue by hf-krechan** [bo4e/BO4E-python#633]
Since the BO4E workshop of 05.10.2023 all attributes are optional.
Therefore, a distinction now no longer makes sense.

**Comment by hf-kklein** [comment]
https://github.com/bo4e/BO4E-python/pull/623/files <-- hasn't this been addressed already?

**Comment by hf-krechan** [comment]
oh nice, thanks for the hint :)
