### ISSUE TITLE
Erweiterung des Enums `Anrede`

### ISSUE THREAD

**Issue by hf-krechan** [bo4e/BO4E-python#657]
**Die fachliche Anforderung**

Ich möchte gerne weitere Anreden nutzen können für die Kommunikation.

**Gibt es schon eine Idee zur Umsetzung?**

Das ENUM `Anrede` soll um die Werte
* `FAMILIE`
* `ERBENGEMEINSCHAFT`
* `GRUNDSTUECKGEMEINSCHAFT`
* `DR`

erweitert werden.

**Comment by hf-fvesely** [comment]
Die ersten drei nehmen wir im ENUM auf, aber DR wird bereits über das ENUM Titel abgebildet
