### ISSUE TITLE
`Mengeneinheit.KWHK` fehlt

### ISSUE THREAD

**Issue by hf-kklein** [bo4e/BO4E-python#757]
https://github.com/bo4e/BO4E-python/blob/76cc35bcc32ae248b906d8b1288f8b691b27f4da/src/bo4e/enum/mengeneinheit.py#L6

kWh/K (Kilowatt-Stunde pro Kelvin)

**Comment by hf-krechan** [comment]
können wir gerne machen, woher kommt diese Anforderung? ^^
