### ISSUE TITLE
Remove old code `com.Sigmoidparameter.calculate(...)`

### ISSUE THREAD

**Issue by lord-haffi** [bo4e/BO4E-python#791]
This piece of code is from 2021. Since we kicked all validation logic besides basic type checking, we may want to get rid of it.
Please give thumbs up or down or comment your thoughts on it.

**Comment by hf-kklein** [comment]
fine for me, but does it hurt?

**Comment by hf-kklein** [comment]
well then: https://github.com/bo4e/BO4E-python/pull/793
