### ISSUE TITLE
Contributing.MD nicht erreichbar

### ISSUE THREAD

**Issue by EWPStanislavKhodorov** [bo4e/BO4E-python#828]
Hallo zusammen,

ich würde gern erfahren, wie Beiträge zum Modell contributed werden können. 
Leider ist die verlinkte contributing.MD nicht erreichbar.
Lässt sich das beheben?

Parallel mache ich gleich einen Issue auf für die fachliche idee.

Danke und beste Grüße
SK

**Comment by hf-krechan** [comment]
Hallo @EWPStanislavKhodorov 
wir haben die Tage die Dokumentation etwas aufgeräumt und dabei die contributing Datei in den docs Ordner umgezogen.

Die Information über Contributing ist nun direkt in der Dokumentation: https://bo4e.github.io/BO4E-python/latest/contributing_guide.html

**Comment by hf-krechan** [comment]
Wenn das für dich passt, kannst du dieses Ticket gerne schließen.

**Comment by EWPStanislavKhodorov** [comment]
Jau, ich lese mir das nachgangs durch und schiebe einen pullrequest auf die ReadMe Verlinkung rein - Danke Dir :)
