### ISSUE TITLE
Ausbau der Lokationstypen gemäß der Codeliste für Lokationsbündelstrukturen

### ISSUE THREAD

**Issue by EWPStanislavKhodorov** [bo4e/BO4E-python#829]
Hallo zusammen,

beim Durchgehen der BOs fiel mir auf, dass in 
https://github.com/bo4e/BO4E-python/blob/main/src/bo4e/enum/lokationstyp.py
lediglich MALO und MELO sind.

Mit der Kommenden Version der MaKo und der Einführung der Lokationsbündelstrukturen hätte ich das mit "NELO" und "TR" ergänzt.
Leider kann ich dazu nicht auf den Contributing Guide zurückgreifen.

Bei Anmerkungen gerne austauschen!

Danke und beste Grüße
SK

**Comment by hf-krechan** [comment]
Der Contributing Guide ist in die Dokumentation gewandert: https://bo4e.github.io/BO4E-python/latest/contributing_guide.html

Das mit der Erweiterung des enums ist ein sehr guter Punkt.
Ich kann dazu schnell einen PR aufmachen

**Comment by hf-krechan** [comment]
Ich habe einen PR erstellt der die Netzlokation und Technische Ressource ergänzt.

Vielen Dank für den Hinweis
